services:
  as400-mockup:
    build: .
    volumes:
      - ./config.json:/app/config.json
      - ./schema_sample.json:/app/schema_sample.json
      - ./mockup_profile_sample.json:/app/mockup_profile_sample.json
      - ./lib:/app/lib
    stdin_open: true
    tty: true
    command: python main.py
